camera:
  index: 0

video:
  dest_dir: output
  fps: 5
  seconds: 10
  file_format: st.EStVideoFileFormat.AVI2
  file_compression: st.EStVideoFileCompression.MotionJPEG
  width: 1920  # FIXED
  height: 1200  # FIXED
